import express from 'express';
import fs from 'node:fs';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import dns from 'node:dns/promises';
import Database from 'better-sqlite3';
import {renderLanding} from './landing.mjs';
const app=express(); app.use(express.json({limit:'1mb'}));const adminHost=String(process.env.ADMIN_HOST||'').toLowerCase();app.use(['/admin','/api'],(q,r,next)=>{if(!adminHost)return next();const host=String(q.get('x-forwarded-host')||q.get('host')||'').split(':')[0].toLowerCase();return host===adminHost?next():r.status(404).send('Not found')});
const appDir=path.dirname(fileURLToPath(import.meta.url));const dataDir=process.env.DATA_DIR?path.resolve(process.env.DATA_DIR):appDir;fs.mkdirSync(dataDir,{recursive:true});const file=path.join(dataDir,'data.json');
const seed={domains:[],links:[],events:[],page:{slug:'profile',name:'Your profile',bio:'Add a short description',accent:'#7c5cff',blocks:[]}};
function load(){try{return JSON.parse(fs.readFileSync(file,'utf8'))}catch{return structuredClone(seed)}} let db=load();
const save=()=>fs.writeFileSync(file,JSON.stringify(db,null,2));
const hashPassword=password=>{const salt=crypto.randomBytes(16).toString('hex');return{salt,hash:crypto.scryptSync(password,salt,64).toString('hex')}};
if(!db.auth)db.auth={sessionSecret:crypto.randomBytes(32).toString('hex')};if(process.env.ADMIN_PASSWORD&&!db.auth.hash)Object.assign(db.auth,hashPassword(process.env.ADMIN_PASSWORD));save();
const trackingTarget=String(process.env.TRACKING_CNAME||'tracker.your-service.com').toLowerCase();for(const domain of db.domains){if(!domain.verificationToken)domain.verificationToken='rk_verify_'+crypto.randomBytes(12).toString('hex');domain.verificationHost='_routekit-verification.'+domain.host;domain.target=trackingTarget}save();
const parseCookie=(header,name)=>String(header||'').split(';').map(x=>x.trim().split('=')).find(x=>x[0]===name)?.slice(1).join('=');
const sessionToken=()=>{const payload=Buffer.from(JSON.stringify({exp:Date.now()+86400000})).toString('base64url');const sig=crypto.createHmac('sha256',db.auth.sessionSecret).update(payload).digest('base64url');return payload+'.'+sig};
const validSession=token=>{try{const[payload,sig]=String(token).split('.');const expected=crypto.createHmac('sha256',db.auth.sessionSecret).update(payload).digest();const actual=Buffer.from(sig,'base64url');return actual.length===expected.length&&crypto.timingSafeEqual(actual,expected)&&JSON.parse(Buffer.from(payload,'base64url')).exp>Date.now()}catch{return false}};
const verifyPassword=password=>{if(!db.auth?.hash)return false;const actual=crypto.scryptSync(String(password),db.auth.salt,64);const expected=Buffer.from(db.auth.hash,'hex');return actual.length===expected.length&&crypto.timingSafeEqual(actual,expected)};
const analyticsDb=new Database(path.join(dataDir,'analytics.db'));analyticsDb.pragma('journal_mode = WAL');analyticsDb.pragma('synchronous = NORMAL');
analyticsDb.exec(`CREATE TABLE IF NOT EXISTS click_events(id TEXT PRIMARY KEY,link_id TEXT NOT NULL,route_id TEXT,visitor_id TEXT NOT NULL,country TEXT NOT NULL DEFAULT 'Unknown',region TEXT NOT NULL DEFAULT 'Unknown',city TEXT NOT NULL DEFAULT 'Unknown',device TEXT NOT NULL,device_model TEXT NOT NULL DEFAULT 'Unknown',os TEXT NOT NULL,browser TEXT NOT NULL,source TEXT NOT NULL,referrer TEXT NOT NULL,destination TEXT NOT NULL,created_at TEXT NOT NULL);CREATE INDEX IF NOT EXISTS idx_click_created ON click_events(created_at DESC);CREATE INDEX IF NOT EXISTS idx_click_link ON click_events(link_id,created_at DESC);CREATE INDEX IF NOT EXISTS idx_click_visitor ON click_events(visitor_id);`);
const insertEvent=analyticsDb.prepare(`INSERT OR IGNORE INTO click_events(id,link_id,route_id,visitor_id,country,region,city,device,device_model,os,browser,source,referrer,destination,created_at) VALUES(@id,@linkId,@routeId,@visitorId,@country,@region,@city,@device,@deviceModel,@os,@browser,@source,@referrer,@destination,@at)`);
app.get('/api/health',(_q,r)=>r.json({ok:true,database:'sqlite',time:new Date().toISOString()}));
if(db.events?.length){const migrate=analyticsDb.transaction(rows=>rows.forEach(e=>insertEvent.run({routeId:null,visitorId:e.id,region:'Unknown',city:'Unknown',deviceModel:'Unknown',os:'Unknown',browser:'Unknown',source:'Direct',destination:'Unknown',...e})));migrate(db.events);delete db.events;save()}
app.get('/api/auth/status',(q,r)=>r.json({authenticated:validSession(parseCookie(q.get('cookie'),'rk_admin')),needsSetup:!db.auth?.hash}));
app.post('/api/auth/setup',(q,r)=>{if(db.auth?.hash)return r.status(409).json({error:'Admin password is already configured'});if(typeof q.body.password!=='string'||q.body.password.length<10)return r.status(400).json({error:'Use at least 10 characters'});Object.assign(db.auth,hashPassword(q.body.password));save();r.cookie('rk_admin',sessionToken(),{httpOnly:true,sameSite:'strict',secure:process.env.NODE_ENV==='production',maxAge:86400000,path:'/'}).json({ok:true})});
app.post('/api/auth/login',(q,r)=>{if(!verifyPassword(q.body.password))return r.status(401).json({error:'Invalid password'});r.cookie('rk_admin',sessionToken(),{httpOnly:true,sameSite:'strict',secure:process.env.NODE_ENV==='production',maxAge:86400000,path:'/'}).json({ok:true})});
app.post('/api/auth/logout',(_q,r)=>r.clearCookie('rk_admin',{path:'/'}).json({ok:true}));
app.use('/api',(q,r,next)=>validSession(parseCookie(q.get('cookie'),'rk_admin'))?next():r.status(401).json({error:'Authentication required'}));
app.get('/api/state',(_q,r)=>r.json({...db,auth:undefined}));
app.get('/api/analytics',(q,r)=>{const days=Math.min(365,Math.max(1,Number(q.query.days)||30));const limit=Math.min(500,Math.max(1,Number(q.query.limit)||100));const offset=Math.max(0,Number(q.query.offset)||0);const since=new Date(Date.now()-days*86400000).toISOString();const where=['created_at >= ?'];const args=[since];if(q.query.linkId){where.push('link_id = ?');args.push(String(q.query.linkId))}if(q.query.country){where.push('country = ?');args.push(String(q.query.country))}if(q.query.source){where.push('source = ?');args.push(String(q.query.source))}const clause=where.join(' AND ');const summary=analyticsDb.prepare(`SELECT COUNT(*) clicks,COUNT(DISTINCT visitor_id) unique_visitors,COUNT(DISTINCT country) countries FROM click_events WHERE ${clause}`).get(...args);const events=analyticsDb.prepare(`SELECT * FROM click_events WHERE ${clause} ORDER BY created_at DESC LIMIT ? OFFSET ?`).all(...args,limit,offset);const daily=analyticsDb.prepare(`SELECT substr(created_at,1,10) day,COUNT(*) clicks,COUNT(DISTINCT visitor_id) unique_visitors FROM click_events WHERE ${clause} GROUP BY day ORDER BY day`).all(...args);const countries=analyticsDb.prepare(`SELECT country,COUNT(*) clicks FROM click_events WHERE ${clause} GROUP BY country ORDER BY clicks DESC LIMIT 20`).all(...args);const sources=analyticsDb.prepare(`SELECT source,COUNT(*) clicks FROM click_events WHERE ${clause} GROUP BY source ORDER BY clicks DESC LIMIT 20`).all(...args);r.json({summary,events,daily,countries,sources,days,limit,offset})});
function safeDestination(value){if(typeof value!=='string')return false;if(value.startsWith('/p/'))return true;try{const u=new URL(value);return u.protocol==='https:'&&!['localhost','127.0.0.1','0.0.0.0','::1'].includes(u.hostname)&&!/^10\.|^192\.168\.|^172\.(1[6-9]|2\d|3[01])\./.test(u.hostname)}catch{return false}}
function osOf(ua){if(/iphone|ipad|ios/i.test(ua))return'iOS';if(/android/i.test(ua))return'Android';if(/windows/i.test(ua))return'Windows';if(/macintosh|mac os/i.test(ua))return'macOS';return'Other'}
function browserOf(ua){if(/Edg\//i.test(ua))return'Edge';if(/OPR\//i.test(ua))return'Opera';if(/Chrome\//i.test(ua))return'Chrome';if(/Firefox\//i.test(ua))return'Firefox';if(/Safari\//i.test(ua))return'Safari';return'Other'}
function modelOf(ua){const android=ua.match(/Android[^;]*;\s*([^;)]+?)(?:\s+Build\/|;|\))/i);if(android)return android[1].trim();if(/iPhone/i.test(ua))return'iPhone';if(/iPad/i.test(ua))return'iPad';return'Unknown'}
const INAPP_PATTERNS=[[/Instagram/i,'instagram'],[/Threads/i,'threads'],[/FBAN|FBAV|FB_IAB|FBIOS/i,'facebook'],[/Messenger/i,'messenger'],[/LinkedInApp/i,'linkedin'],[/TikTok|BytedanceWebview|musical_ly|Bytedance/i,'tiktok'],[/Twitter/i,'twitter'],[/Snapchat/i,'snapchat'],[/Pinterest/i,'pinterest'],[/Reddit/i,'reddit']];
const GESTURE_APPS=new Set(['twitter','tiktok','snapchat','linkedin','pinterest','reddit']);
function inappOf(ua){for(const[re,app]of INAPP_PATTERNS){if(re.test(ua))return app}return null}
function landingFields(body){const on=Boolean(body&&body.landing);const mode=body&&body.landingMode==='app'?'app':'browser';const str=(v,max)=>typeof v==='string'?v.trim().slice(0,max):'';const scheme=str(body&&body.landingScheme,120);const n=Number(body&&body.landingCountdown);const cd=Number.isFinite(n)?Math.min(15,Math.max(0,Math.floor(n))):2;return{landing:on,landingMode:on?mode:'browser',landingScheme:on&&mode==='app'&&/^[a-z][a-z0-9+.-]*:\/\//i.test(scheme)?scheme:'',landingHeading:on?str(body&&body.landingHeading,80):'',landingSubtext:on?str(body&&body.landingSubtext,140):'',landingButton:on?str(body&&body.landingButton,40):'',landingCopy:on?str(body&&body.landingCopy,40):'',landingDirect:on?str(body&&body.landingDirect,40):'',landingCountdown:on?cd:2}}
function primaryScheme(link,app,platform,pageUrl,destination){if(link.landingMode==='app'&&link.landingScheme){if(platform==='ios')return link.landingScheme;const m=link.landingScheme.match(/^([a-z][a-z0-9+.-]*):\/\/(.*)$/i);if(m)return'intent://'+m[2]+'#Intent;scheme='+m[1].toLowerCase()+';S.browser_fallback_url='+encodeURIComponent(destination)+';end';return link.landingScheme}if(platform==='ios'){if(app==='instagram'||app==='threads')return'instagram://extbrowser/?url='+encodeURIComponent(pageUrl);return'x-safari-'+pageUrl}const u=new URL(pageUrl);return'intent://'+u.host+u.pathname+u.search+'#Intent;scheme=https;S.browser_fallback_url='+encodeURIComponent(destination)+';end'}
function landingPage(link,app,platform,pageUrl,destination){const gestureOnly=platform==='ios'&&GESTURE_APPS.has(app);const fallback=destination+(destination.includes('?')?'&':'?')+'_inapp_escaped=1';return renderLanding({auto:!gestureOnly,countdown:gestureOnly?0:link.landingCountdown,primary:primaryScheme(link,app,platform,pageUrl,destination),destination,fallback,heading:link.landingHeading||'Opening in your browser…',subtext:link.landingSubtext||'You are being redirected outside this app for the best experience.',button:link.landingButton||'Continue',copyLabel:link.landingCopy||'Copy link',directLabel:link.landingDirect||'Continue in browser',initials:(link.name||'W').split(' ').map(x=>x[0]).join('').slice(0,2)||'W'})}
function cookieOf(header,name){return parseCookie(header,name)}
app.post('/api/links',(q,r)=>{if(!db.domains.some(x=>x.host===q.body.domain&&x.status==='active'))return r.status(400).json({error:'Select a verified active domain'});if(db.links.some(x=>x.domain===q.body.domain&&x.slug===q.body.slug))return r.status(409).json({error:'This path already exists on the selected domain'});if(!safeDestination(q.body.destination))return r.status(400).json({error:'Use a public HTTPS destination'});const x={id:crypto.randomUUID(),clicks:0,status:'active',rules:0,routes:[],...q.body,...landingFields(q.body)};db.links.unshift(x);save();r.status(201).json(x)});
app.patch('/api/links/:id',(q,r)=>{const i=db.links.findIndex(x=>x.id===q.params.id);if(i<0)return r.sendStatus(404);if(q.body.destination&&!safeDestination(q.body.destination))return r.status(400).json({error:'Unsafe destination'});if(q.body.routes?.some(x=>!safeDestination(x.destination)))return r.status(400).json({error:'Unsafe route destination'});db.links[i]={...db.links[i],...q.body,...landingFields(q.body)};db.links[i].rules=db.links[i].routes?.length||0;save();r.json(db.links[i])});
app.delete('/api/links/:id',(q,r)=>{db.links=db.links.filter(x=>x.id!==q.params.id);save();r.sendStatus(204)});
app.post('/api/domains',(q,r)=>{const host=String(q.body.host||'').trim().toLowerCase().replace(/^https?:\/\//,'').replace(/\/$/,'');if(!/^(?=.{4,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/.test(host))return r.status(400).json({error:'Enter a valid hostname without https:// or a path'});if(db.domains.some(x=>x.host===host))return r.status(409).json({error:'This domain is already connected'});const x={id:crypto.randomUUID(),host,status:'pending',ssl:false,verificationToken:'rk_verify_'+crypto.randomBytes(12).toString('hex'),verificationHost:'_routekit-verification.'+host,target:trackingTarget};db.domains.push(x);save();r.status(201).json(x)});
app.post('/api/domains/:id/verify',async(q,r)=>{const domain=db.domains.find(x=>x.id===q.params.id);if(!domain)return r.sendStatus(404);try{const timeout=new Promise((_,reject)=>setTimeout(()=>reject(Object.assign(Error('DNS timeout'),{code:'ETIMEOUT'})),5000));const records=(await Promise.race([dns.resolveTxt(domain.verificationHost),timeout])).flat();if(!records.includes(domain.verificationToken))return r.status(409).json({error:'Verification TXT record was not found yet',domain});domain.status='active';domain.verifiedAt=new Date().toISOString();domain.ssl=process.env.NODE_ENV!=='production'?false:Boolean(process.env.TLS_MANAGED);save();r.json(domain)}catch(error){r.status(409).json({error:'DNS record is not visible yet. DNS propagation can take time.',code:error.code,domain})}});
app.delete('/api/domains/:id',(q,r)=>{const domain=db.domains.find(x=>x.id===q.params.id);if(!domain)return r.sendStatus(404);const used=db.links.filter(x=>x.domain===domain.host);if(used.length)return r.status(409).json({error:`Domain is used by ${used.length} link(s). Reassign or delete them first.`});db.domains=db.domains.filter(x=>x.id!==q.params.id);save();r.sendStatus(204)});
app.put('/api/page',(q,r)=>{db.page=q.body;save();r.json(db.page)});
app.use((q,r,next)=>{if(q.method!=='GET'||!/^\/[a-zA-Z0-9_-]+\/?(?:\?.*)?$/.test(q.url)||q.url.split('?')[0].replace(/\/$/,'')==='/admin')return next();const slug=q.url.split('?')[0].replaceAll('/','');const host=String(q.get('x-forwarded-host')||q.get('host')||'').split(':')[0].toLowerCase();const local=['localhost','127.0.0.1'].includes(host);if(!db.links.some(x=>x.slug===slug&&x.status==='active'&&(local||x.domain.toLowerCase()===host)))return r.status(404).send('Link not found on this domain');q.url='/r/'+slug;next()});
app.get('/r/:slug',(q,r)=>{const link=db.links.find(x=>x.slug===q.params.slug&&x.status==='active');if(!link)return r.status(404).send('Link not found');const country=(q.get('cf-ipcountry')||q.get('x-vercel-ip-country')||'Unknown').toUpperCase();const region=q.get('x-vercel-ip-country-region')||q.get('cf-region')||'Unknown';const city=decodeURIComponent(q.get('x-vercel-ip-city')||q.get('cf-ipcity')||'Unknown');const ua=q.get('user-agent')||'';const device=/mobile|android|iphone/i.test(ua)?'Mobile':/tablet|ipad/i.test(ua)?'Tablet':'Desktop';const os=osOf(ua);const referrer=q.get('referer')||'';let source=String(q.query.utm_source||'');if(!source&&referrer){try{source=new URL(referrer).hostname}catch{}}if(!source)source='Direct';const route=(link.routes||[]).find(x=>(x.country==='Any'||x.country===country)&&(x.device==='Any'||x.device===device)&&(x.os==='Any'||x.os===os));const destination=route?.destination||link.destination;if(!safeDestination(destination))return r.status(409).send('Destination blocked');let visitorId=cookieOf(q.get('cookie'),'rk_vid');if(!visitorId){visitorId=crypto.randomUUID();r.cookie('rk_vid',visitorId,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:31536000000})}insertEvent.run({id:crypto.randomUUID(),linkId:link.id,routeId:route?.id||null,visitorId,country,region,city,device,deviceModel:modelOf(ua),os,browser:browserOf(ua),source,referrer:referrer||'Direct',destination,at:new Date().toISOString()});link.clicks++;save();const headers={'Cache-Control':'no-store','Referrer-Policy':'strict-origin-when-cross-origin','X-Content-Type-Options':'nosniff'};const app=link.landing?inappOf(ua):null;if(link.landing&&app&&q.query._inapp_escaped===undefined){const host=String(q.get('x-forwarded-host')||q.get('host')||'').split(':')[0].toLowerCase();const pageUrl='https://'+host+q.originalUrl;const platform=/iPhone|iPad|iPod/.test(ua)?'ios':'android';return r.set(headers).send(landingPage(link,app,platform,pageUrl,destination))}r.set(headers).redirect(302,destination)});
app.get('/p/:slug',(q,r)=>{if(q.params.slug!==db.page.slug)return r.sendStatus(404);const p=db.page;const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));r.send(`<!doctype html><meta name="viewport" content="width=device-width"><title>${esc(p.name)}</title><style>*{box-sizing:border-box}body{margin:0;background:#0b0b12;color:#fff;font:16px Inter,system-ui;min-height:100vh;display:grid;place-items:center}.c{width:min(92%,440px);text-align:center}.av{width:88px;height:88px;border-radius:28px;margin:auto;background:linear-gradient(135deg,${p.accent},#ff7a59);display:grid;place-items:center;font-size:28px;font-weight:800}h1{margin:20px 0 6px}p{color:#a7a7b8;margin:0 0 28px}.a{display:block;color:#fff;text-decoration:none;background:#191925;border:1px solid #303040;padding:17px;margin:12px 0;border-radius:16px;font-weight:650}.a:hover{border-color:${p.accent};transform:translateY(-1px)}</style><main class="c"><div class="av">${esc(p.name).split(' ').map(x=>x[0]).join('').slice(0,2)}</div><h1>${esc(p.name)}</h1><p>${esc(p.bio)}</p>${p.blocks.map(b=>`<a class="a" href="${esc(b.url)}">${esc(b.title)}</a>`).join('')}</main>`)});
const dist=fileURLToPath(new URL('./dist',import.meta.url));if(fs.existsSync(dist)){app.use('/assets',express.static(path.join(dist,'assets'),{immutable:true,maxAge:'1y'}));const adminIndex=(_q,r)=>r.sendFile(path.join(dist,'index.html'));app.get('/admin',adminIndex);app.get('/admin/*',adminIndex)}
const port=Number(process.env.PORT)||8787;app.listen(port,()=>console.log(`Waylo on http://localhost:${port}`));
